### ISSUE TITLE
Facebook SDK version

### ISSUE THREAD

**Issue by pitrrs** [venca-x/social-login#1]
Hi,

please specify version of "facebook/php-sdk-v4" in composer.json. Now is version 4.1 and there is many INCOMPATIBLE changes.

For example: removed Facebook\FacebookSession etc...

I used this version: 4.0.12 (latest compatible version with your Nette plugin)

Cheers dude :)

// Nevím, jestli jsi čech, tak raději anglicky

**Comment by venca-x** [comment]
Fixed https://github.com/venca-x/social-login/commit/a4d09725dc76ebb2a170661774dc2735b893739a
