### ISSUE TITLE
GoogleLogin state helper is not defined.

### ISSUE THREAD

**Issue by dada-amater** [venca-x/social-login#12]
When we call `google->setState($state)`, we get an error:
`Cannot read an undeclared property VencaX\GoogleLogin::$helper.`

It is caused by missing (undefined) helper here:
https://github.com/venca-x/social-login/blob/master/src/GoogleLogin.php#L58

**Comment by dada-amater** [comment]
Please, could you make a new release?

**Comment by venca-x** [comment]
Yea, i released 1.2.2 - https://packagist.org/packages/venca-x/social-login#1.2.2
