### ISSUE TITLE
kertz/twitteroauth dependency is on master

### ISSUE THREAD

**Issue by racinmat** [venca-x/social-login#15]
Hi, is there plan to use stable version of this dependency? Or maybe more widely used package as https://github.com/abraham/twitteroauth? 
Or is there specific reason for this dependency and running on master?
Thanks.

**Comment by venca-x** [comment]
Hello,
on packagist is kertz/twitteroauth without versions :-( https://packagist.org/packages/kertz/twitteroauth
composer.json takes version from packagist

**Comment by racinmat** [comment]
And why is this fork used instead of the main repo? Are there any notable differences?

**Comment by venca-x** [comment]
Oh, sorry. I see. I will switch from **kertz/twitteroauth** to stable **abraham/twitteroauth**
