### ISSUE TITLE
Fatal error in Twitter implementation

### ISSUE THREAD

**Issue by jannovy** [venca-x/social-login#18]
Implementation of TwitterOAuth failing on **Class 'TwitterOAuth' not found**

Seems that https://github.com/abraham/twitteroauth made a few changes around https://twitteroauth.com/

**Comment by venca-x** [comment]
Hello,
thanks. I fixed it in dev-master and 1.2.7 version.
Please try it.

**Comment by jannovy** [comment]
Thank you very much for the update.

First, I'm not able to get Twitter authorization gateway until I change this in TwitterLogin.php::74

`
'oauth_token' => $this->params['callbackURL'],
`
to
`
'oauth_token' => $token,
`

Second, the request on my callback page failed on **Call to undefined method Abraham\TwitterOAuth\TwitterOAuth::getAccessToken()** in TwitterLogin.php::101

**Comment by venca-x** [comment]
I fixed it :-) Try version 1.2.8 or master

**Comment by jannovy** [comment]
Thank you. Working well.
