### ISSUE TITLE
Getting users email from twitterOAuth

### ISSUE THREAD

**Issue by jannovy** [venca-x/social-login#20]
Is there any option how to get a users email from twitter api ? I have to explicitly request an email from account/verify_credentials endpoint. 

But there is no way in TwitterLogin class to pass anything as a second parameter for:

`
$user_info = $this->twitterOAuth->get('account/verify_credentials', ['include_email' => true]);
`

The second parameter **['include_email' => true]** does the magic.

**Comment by venca-x** [comment]
Hi,
should it be the default? Or optional?

**Comment by jannovy** [comment]
Hello, 
the optional method will be better solution.

Thanks a lot!

**Comment by venca-x** [comment]
Can you please test in master branch?
In function: getMe($oauthToken, $oauthVerifier, $includeEmail = false) is parameter includeEmail.
It doesn't work for me :-( See you problem?

**Comment by jannovy** [comment]
Working great. Thank you. Check your app on developer.twitter.com and make sure that Enable 3-legged OAuth and Request email address from users options are checked.
