### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by dada-amater** [venca-x/social-login#21]
Hello, thank you for your great addon. We would like to upgrade to PHP 8, but there is one blocker: dependency of `facebook/graph-sdk`. That package is not maintained anymore. Would you consider replacing this package aby another one, for example `league/oauth2-facebook`?

**Comment by venca-x** [comment]
@dada-amater please, try branch feature/php-8

**Comment by dada-amater** [comment]
Actually, we don't use FB login, because we provide an adult site and FB banned us :-)
